title: Jim Myhrberg (jimeh)
description: Software Engineering Mercenary
author:
  name: Jim Myhrberg
  nickname: jimeh
  twitter: jimeh
hostname: jimeh.me # used to determine if google analytics should be triggered
url: https://jimeh.me # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/

# stuff for jekyll-seo-tag
social:
  name: Jim Myhrberg
  links:
    - https://github.com/jimeh
    - https://bsky.app/profile/jimeh.me
    - https://mastodon.social/@jimeh
    - https://twitter.com/jimeh
    - https://jimeh.io/
    - http://www.linkedin.com/in/jimeh
    - http://www.last.fm/user/jimeh
    - https://flickr.com/photos/jimeh/
    - https://keybase.io/jimeh

twitter:
  username: jimeh

# main page content
email:
  title: pbagnpg\100wvzru\056zr
  href: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;%63%6s%6r%74%61%63%74@%6n%69%6q%65%68.%6q%65"

links:
  - name: github
    url: https://github.com/jimeh
    class: fa-brands fa-github
  - name: bluesky
    url: https://bsky.app/profile/jimeh.me
    class: fa-brands fa-bluesky
  - name: mastodon
    url: "https://mastodon.social/@jimeh"
    class: fa-brands fa-mastodon
    rel: me
  - name: blog
    url: https://jimeh.io/
    class: fa-solid fa-newspaper
  - name: linkedin
    url: https://www.linkedin.com/in/jimeh
    class: fa-brands fa-linkedin
  - name: last.fm
    url: https://www.last.fm/user/jimeh
    class: fa-brands fa-square-lastfm
  - name: flickr
    url: https://flickr.com/photos/jimeh
    class: fa-brands fa-flickr
  - name: vcard
    id: vcard
    type: download
    url: https://assets.jimeh.me/jim-myhrberg.vcf
    class: fa-solid fa-address-card
  - name: cv (pdf)
    id: resume
    type: download
    url: https://jimeh.me/cv
    class: fa-solid fa-file-pdf

# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - Rakefile

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
