# Site settings
title: Jim Myhrberg (jimeh)
name: Jim Myhrberg
nickname: jimeh
email: pbagnpg\100wvzru\056zr
mailto: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;%63%6s%6r%74%61%63%74@%6n%69%6q%65%68.%6q%65"
description: Crazy-Ass Software Engineering Mercenary
baseurl: "" # the subpath of your site, e.g. /blog/
hostname: jimeh.me # used to determine if google analytics should be triggered
url: http://jimeh.me # the base hostname & protocol for your site
permalink: /:title/
blog_url: https://jimeh.io/
cv_url: http://assets.jimeh.me/jim-myhrberg-cv.pdf
vcard_url: http://assets.jimeh.me/jim-myhrberg.vcf
twitter_username: jimeh
github_username: jimeh
linkedin_username: jimeh
facebook_username: jimeh
flickr_username: jimeh
lastfm_username: jimeh

# Build settings
markdown: kramdown
